import {
  evasiveManeuvers,
  portableWormhole,
  reinforce,
} from "../../../data/active-skills";
import { autocannon } from "../../../data/weapons";
import { SkillTree } from "../skill-tree.model";

export const tier0: SkillTree = [
  {
    id: "t0-ship|base",
    connected: [],
    depth: 0,
    index: 0,
    type: "weapon",
    weapon: autocannon,
  },
  {
    id: "t0-ship|red-1",
    connected: ["t0-ship|base"],
    depth: 1,
    index: -3,
    name: "Ship Rating +",
    type: "passive",
    colour: "r",
    statAdjustments: {
      maxHP: { global: { addition: 10 } },
      damage: { global: { addition: 1 } },
    },
  },
  {
    id: "t0-ship|red-2-defensive",
    connected: ["t0-ship|red-1"],
    depth: 2,
    index: -4,
    name: "Armour",
    type: "passive",
    colour: "r",
    statAdjustments: {
      armour: { global: { addition: 10 } },
    },
  },
  {
    id: "t0-ship|red-2-offensive",
    connected: ["t0-ship|red-1"],
    depth: 2,
    index: -2,
    name: "Firepower",
    type: "passive",
    colour: "r",
    statAdjustments: {
      damage: { global: { multiplier: 0.15 } },
    },
  },
  {
    id: "t0-ship|red-capstone",
    connected: ["t0-ship|red-2-defensive", "t0-ship|red-2-offensive"],
    depth: 3,
    index: -3,
    type: "tech",
    colour: "r",
    tech: reinforce,
  },
  {
    id: "t0-ship|green-1",
    connected: ["t0-ship|base"],
    depth: 1,
    index: 0,
    name: "Pilot Rating +",
    type: "passive",
    colour: "g",
    statAdjustments: {
      maxHP: { global: { addition: 10 } },
      critChance: { global: { addition: 0.1 } },
    },
  },
  {
    id: "t0-ship|green-2-defensive",
    connected: ["t0-ship|green-1"],
    depth: 2,
    index: -1,
    name: "Evasion",
    type: "passive",
    colour: "g",
    statAdjustments: {
      evadeChance: { global: { addition: 0.15 } },
    },
  },
  {
    id: "t0-ship|green-2-offensive",
    connected: ["t0-ship|green-1"],
    depth: 2,
    index: 1,
    name: "Rate of Fire",
    type: "passive",
    colour: "g",
    statAdjustments: {
      rof: { global: { multiplier: 0.15 } },
    },
  },
  {
    id: "t0-ship|green-capstone",
    connected: ["t0-ship|green-2-defensive", "t0-ship|green-2-offensive"],
    depth: 3,
    index: 0,
    type: "tech",
    colour: "g",
    tech: evasiveManeuvers,
  },
  {
    id: "t0-ship|blue-1",
    connected: ["t0-ship|base"],
    depth: 1,
    index: 3,
    name: "Tech Rating +",
    type: "passive",
    colour: "b",
    statAdjustments: {
      maxHP: { global: { addition: 10 } },
      // TODO figure out stat here. area of effect?
    },
  },
  {
    id: "t0-ship|blue-2-defensive",
    connected: ["t0-ship|blue-1"],
    depth: 2,
    index: 2,
    name: "Energy Shields",
    type: "passive",
    colour: "b",
    statAdjustments: {
      maxShields: { global: { addition: 10 } },
    },
  },
  {
    id: "t0-ship|blue-2-offensive",
    connected: ["t0-ship|blue-1"],
    depth: 2,
    index: 4,
    name: "Tech Recovery",
    type: "passive",
    colour: "b",
    statAdjustments: {
      rechargeSpeed: { global: { multiplier: 0.15 } },
    },
  },
  {
    id: "t0-ship|blue-capstone",
    connected: ["t0-ship|blue-2-defensive", "t0-ship|blue-2-offensive"],
    depth: 3,
    index: 3,
    type: "tech",
    colour: "b",
    tech: portableWormhole,
  },
];
