import { ACTIVE_SKILLS } from "../../../data/active-skills";
import { WEAPONS } from "../../../data/weapons";
import { SkillTree } from "../skill-tree.model";

export const tier0: SkillTree = [
  {
    id: "base",
    connected: [],
    depth: 0,
    index: 0,
    type: "weapon",
    weapon: WEAPONS.cannon,
  },
  {
    id: "red-1",
    connected: ["base"],
    depth: 1,
    index: -3,
    name: "Ship Rating +",
    type: "passive",
    colour: "r",
    statAdjustments: {
      maxHP: { global: { addition: 10, multiplier: 0 } },
      damage: { global: { addition: 1, multiplier: 0 } },
    },
  },
  {
    id: "red-2-defensive",
    connected: ["red-1"],
    depth: 2,
    index: -4,
    name: "Armour",
    type: "passive",
    colour: "r",
    statAdjustments: { armour: { global: { addition: 10, multiplier: 0 } } },
  },
  {
    id: "red-2-offensive",
    connected: ["red-1"],
    depth: 2,
    index: -2,
    name: "Firepower",
    type: "passive",
    colour: "r",
    statAdjustments: {
      damage: { global: { addition: 0, multiplier: 0.15 } },
    },
  },
  {
    id: "red-capstone",
    connected: ["red-2-defensive", "red-2-offensive"],
    depth: 3,
    index: -3,
    type: "tech",
    colour: "r",
    tech: ACTIVE_SKILLS.reinforce,
  },
  {
    id: "green-1",
    connected: ["base"],
    depth: 1,
    index: 0,
    name: "Pilot Rating +",
    type: "passive",
    colour: "g",
    statAdjustments: {
      maxHP: { global: { addition: 10, multiplier: 0 } },
      critChance: { global: { addition: 0.1, multiplier: 0 } },
    },
  },
  {
    id: "green-2-defensive",
    connected: ["green-1"],
    depth: 2,
    index: -1,
    name: "Evasion",
    type: "passive",
    colour: "g",
    statAdjustments: {
      evadeChance: { global: { addition: 0.15, multiplier: 0 } },
    },
  },
  {
    id: "green-2-offensive",
    connected: ["green-1"],
    depth: 2,
    index: 1,
    name: "Rate of Fire",
    type: "passive",
    colour: "g",
    statAdjustments: {
      rof: { global: { addition: 0, multiplier: 0.15 } },
    },
  },
  {
    id: "green-capstone",
    connected: ["green-2-defensive", "green-2-offensive"],
    depth: 3,
    index: 0,
    type: "tech",
    colour: "g",
    tech: ACTIVE_SKILLS.evasiveManeuvers,
  },
  {
    id: "blue-1",
    connected: ["base"],
    depth: 1,
    index: 3,
    name: "Tech Rating +",
    type: "passive",
    colour: "b",
    statAdjustments: {
      maxHP: { global: { addition: 10, multiplier: 0 } },
      // TODO figure out stat here. area of effect?
    },
  },
  {
    id: "blue-2-defensive",
    connected: ["blue-1"],
    depth: 2,
    index: 2,
    name: "Energy Shields",
    type: "passive",
    colour: "b",
    statAdjustments: {
      maxShields: { global: { addition: 10, multiplier: 0 } },
    },
  },
  {
    id: "blue-2-offensive",
    connected: ["blue-1"],
    depth: 2,
    index: 4,
    name: "Tech Recovery",
    type: "passive",
    colour: "b",
    statAdjustments: {
      rechargeSpeed: { global: { addition: 0, multiplier: 0.15 } },
    },
  },
  {
    id: "blue-capstone",
    connected: ["blue-2-defensive", "blue-2-offensive"],
    depth: 3,
    index: 3,
    type: "tech",
    colour: "b",
    tech: ACTIVE_SKILLS.portableWormhole,
  },
];
